# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master
pool:
  name: Azure Pipelines

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Management Group'
    ConnectedServiceName: 'ManagementGroup - KuvMG1'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'mg.json'
    deploymentMode: 'Incremental'