# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- task: AzureResourceDeployment@2
  displayName: 'Azure Deployment:Create Or Update Resource Group action on kuvrg'
  inputs:
    azureSubscription: rmd
    subscriptionName: 'c00d16c7-6c1f-4c03-9be1-6934a4c49682'
    resourceGroupName: kuvrg1
    location: 'East Asia'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/vinodkumar3/AppInsight-ARM-Template/master/template.json'
