# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master
pool:
  name: Default

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Resource Group scope'
  inputs:
    ConnectedServiceName: Rmd
    subscriptionName: 'c00d16c7-6c1f-4c03-9be1-6934a4c49682'
    resourceGroupName: kuvrg1df
    location: 'East US'
    csmFile: 'test/resource-group-template.json'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'Rmd'
    action: 'Create Or Update Resource Group'
    subscriptionName: 'c00d16c7-6c1f-4c03-9be1-6934a4c49682'
    resourceGroupName: 'kuvrg1'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'resource-group-template.json'
    deploymentMode: 'Incremental'
    deploymentName: 'aaaaaaaaaaaaaa'
